FORMAT: 1A

# My Api

## Get [/places]

+ Response 200 (application/json)
    
        {
            "places" : [{
                "id" : "fRg5",
                "name" : "Melvin"
                }]
        }